name: docs

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

env:
  PYTHONPATH: src

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3
        with:
          environment-file: "environment.dev.yml"
          cache-downloads: true
          cache-env: true
      - run: pdoc src/ -o docs/
      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
